name = "Rewind Upsilon"
author = "unascribed"
version = "0.4.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f657adfa4e8d3a391ff8eb00631f0293920fca08cf75decac6e5212581eefa7"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"
unsup = "0.2.0"

[options]
acceptable-game-versions = ["1.4.6"]
