name = "Rewind Upsilon"
author = "unascribed"
version = "0.5.5_02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c615976bbc420aab64e8f72ab26cdf73dab516f2bab4e9917c4a02856c7da0f"

[versions]
forge = "6.6.2.534"
liteloader = "1.4.7_00"
minecraft = "1.4.7"
nilloader = "1.3.4"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.4.6"]
