name = "Rewind Upsilon"
author = "unascribed"
version = "0.4.12-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57df0573d6bd69e34b01b5587046bbba6bf381ce1d1e83fb33797a84751a7d75"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"
unsup = "0.2.0"

[options]
acceptable-game-versions = ["1.4.6"]
