# RedPower Tweaks Configuration File
#
# The following options correspond to the default settings as used by
# RPTweaks when no config file is present.

# Adds a button to clear the crafting grid in project tables. This has
# the exact effect as shift-clicking each square in the crafting grid.
adv_bench_clear_btn on

# Prevents things like microblocks and pipes from dropping as items when
# broken in creative mode. I did my best to ensure that objects containing
# other objects (like disk drives, pipes, filters, etc.) dropped their
# contents when broken, but didn't drop themselves. However, since it's
# possible (although unlikely) that contents could be lost as well, the
# option is provided to disable this.
no_creative_drops on

# Fixes screw drivers so right-clicking while sneaking brings up the
# bus ID GUI on redbus components. I have no idea why I'm letting people
# disable this, but meh.
screwdriver on

# Fixes ID auto-assign.
autoassign off

# There is no option to disable the fix for the IO expander, backplane,
# and RAM duplication bug, since disabling it makes no sense.

# There is also no option to disable the fix for the canvas bag item
# duplication bug.
